version: '3.4'
services:
  backend:
    build:
      context: .
      target: backend
  frontend:
    ports:
      - 8080:8080
    build:
      context: .
      target: frontend
    environment:
      - BACKEND_DNS=backend