apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: backend
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: backend
    spec:
      containers:
      - image: agesome2/backend:latest
        name: backend
        env:
        - name: REDIS_DNS
          value: "redis.user15.svc.cluster.local"
        resources: {}
status: {}
