
name: Go CI
on: push
jobs:
  Test:
    runs-on: ubuntu-latest
    container: golang:1.16.7
    steps:
      - name: setup
        uses: actions/checkout@v2
      - name: builder backend
        run: cd backend/ && go build .
      - name: builder frontend
        run: cd frontend/ && go build .
      - name: test backend
        run: cd backend/ && go test
      - name: test frontend
        run: cd frontend/ && go test