
name: Go CI
on: push
jobs:
  Clone-down:
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - name: setup
        uses: actions/checkout@v2
      - uses: actions/upload-artifact@v2
        with:
          name: code
          path: .
  
  Build:
    needs: Clone-down
    runs-on: ubuntu-latest
    container: golang:1.16.7
    steps:
    - uses: actions/download-artifact@v2
      with:
        name: code
        path: .
    - name: builder
      run: cd backend/ && go build .
    - name: frontend
      run: cd frontend/ && go build .
    - name: uploader 
      uses: actions/upload-artifact@v2
      with:
        name: code
        path: .

  Test:
    needs: [Clone-down, Build]
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: code
          path: .
      - name: test backend
        run: cd backend/ && go test
      - name: test frontend
        run: cd frontend/ && go test