env:
  docker_username: ${{ secrets.DOCKER_USERNAME }}
  docker_password: ${{ secrets.DOCKER_PASSWORD }}
name: Go CD
on: 
  push:
    branches:
      - main
jobs:
  Backend:
    runs-on: ubuntu-latest
    steps:
      - name: setup
        uses: actions/checkout@v2
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ env.docker_username }}
          password: ${{ env.docker_password }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: agesome2/backend:latest
          target: backend
  Frontend:
    runs-on: ubuntu-latest
    steps:
      - name: setup
        uses: actions/checkout@v2
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ env.docker_username }}
          password: ${{ env.docker_password }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: agesome2/frontend:latest
          target: frontend